config/routes.rb
Rails.application.routes.draw do
  resources :candidates
  root 'candidates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  validates :name, presence: true
  validates :age, numericality: { greater_than: 29 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, except: [:index, :new, :create]
  def index
    @candidates = Candidate.all
  end 

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(clean_params)

    if @candidate.save
      redirect_to root_path, notice: "Create Success!"        
    else
      render :new
    end
    
  end

  def show

  end

  def edit

  end

  def update
    if @candidate.update(clean_params)
      redirect_to root_path, notice: "Update Success!"
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to root_path, notice: " Deleted!"
  end

  private
  def clean_params
    params.require(:candidate).permit(:name, :party, :age, :policy)
  end

  def find_candidate
    @candidate = Candidate.find_by(id: params["id"])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/edit.html.erb
<h1>Edit Candidate</h1>

<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message|%>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @candidate do |f| %>
  <div>
    <%= f.label :name, "name: "%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :party, "party: "%>
    <%= f.text_field :party %>
  </div>
  <div>
    <%= f.label :age, "age: "%>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.label :policy, "policy: "%>
    <%= f.text_field :policy %>
  </div>
    <%= f.submit%>
<% end %>

app/views/candidates/index.html.erb
<div><%= flash[:notice]  %></div>
<h1>Candidates List</h1>
<h2>  Edit in git</h2>
<% @candidates.each do |candidate|%>
  <ul>
    <li>
      <%= link_to candidate.name, candidate_path(candidate)%>
      <%= link_to "Edit", edit_candidate_path(candidate)%>
      <%= link_to "Delete", candidate_path(candidate), method: :delete, data: {confirm: "R U SURE? "}%>
    </li>
  </ul>

<% end %>

<%= link_to "Add Candidate", new_candidate_path%>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message|%>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @candidate do |f| %>
  <div>
    <%= f.label :name, "name: "%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :party, "party: "%>
    <%= f.text_field :party %>
  </div>
  <div>
    <%= f.label :age, "age: "%>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.label :policy, "policy: "%>
    <%= f.text_field :policy %>
  </div>
    <%= f.submit%>
<% end %>

app/views/candidates/show.html.erb
<% if @candidate %>
  <h1><%= @candidate.name%></h1>
    <ul>
      <li><%= @candidate.party%></li>
      <li><%= @candidate.age%></li>
      <li><%= @candidate.policy%></li>
    </ul>  
<% end %>

<%= link_to "Back to List", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P17</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>